Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Error calculation
err_abs = np.abs(q_abs_analyt - q_abs_fenics) / q_abs_analyt
err_sca = np.abs(q_sca_analyt - q_sca_fenics) / q_sca_analyt
err_ext = np.abs(q_ext_analyt - q_ext_fenics) / q_ext_analyt

if MPI.COMM_WORLD.rank == 0:

    print()
    print(f"The analytical absorption efficiency is {q_abs_analyt}")
    print(f"The numerical absorption efficiency is {q_abs_fenics}")
    print(f"The error is {err_abs*100}%")
    print()
    print(f"The analytical scattering efficiency is {q_sca_analyt}")
    print(f"The numerical scattering efficiency is {q_sca_fenics}")
    print(f"The error is {err_sca*100}%")
    print()
    print(f"The analytical extinction efficiency is {q_ext_analyt}")
    print(f"The numerical extinction efficiency is {q_ext_fenics}")
    print(f"The error is {err_ext*100}%")

    assert err_abs < 0.01
    assert err_sca < 0.01
    assert err_ext < 0.01
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
Input [0;32mIn [16][0m, in [0;36m<cell line: 6>[0;34m()[0m
[1;32m     18[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mThe numerical extinction efficiency is [39m[38;5;132;01m{[39;00mq_ext_fenics[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m     19[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mThe error is [39m[38;5;132;01m{[39;00merr_ext[38;5;241m*[39m[38;5;241m100[39m[38;5;132;01m}[39;00m[38;5;124m%[39m[38;5;124m"[39m)
[0;32m---> 21[0m [38;5;28;01massert[39;00m err_abs [38;5;241m<[39m [38;5;241m0.01[39m
[1;32m     22[0m [38;5;28;01massert[39;00m err_sca [38;5;241m<[39m [38;5;241m0.01[39m
[1;32m     23[0m [38;5;28;01massert[39;00m err_ext [38;5;241m<[39m [38;5;241m0.01[39m

[0;31mAssertionError[0m: 
AssertionError: 

